{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations: 
    {{- .Values.ingress.annotations | toYaml | nindent 4}}
  {{- end }}
  name: {{ default "jhub-ingress" .Values.ingress.name }}
  {{- if .Values.ingress.labels }}
  labels:
    {{- .Values.ingress.labels | toYaml | nindent 4}}
  {{- end }}

spec:
  ingressClassName: nginx
  rules:
    {{- with .Values.ingress }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePortNumber }}
    {{- end }}
{{- end }}